### ISSUE TITLE
Android app wrong button text

### ISSUE THREAD

**Issue by Agazoth** [tmrowco/electricitymap#486]
In version 1.0.2 button text says menu.mapview menu.listview and menu.info

**Comment by corradio** [comment]
That's because we lack a translation for you langage (Danish?)

**Comment by Agazoth** [comment]
Kort
Liste
Info

Den ons. 19. apr. 2017 17.53 skrev Olivier Corradi <notifications@github.com
>:

> That's because we lack a translation for you langage (Danish?)
>

**Comment by Raffox97** [comment]
Should be fixed now #489

**Comment by Agazoth** [comment]
I think you need to upload a new apk to the Play Store before the issue is
solved.

tor. 20. apr. 2017 kl. 08.48 skrev Olivier Corradi <notifications@github.com

**Comment by magol** [comment]
Although there are now localized texts, it still shows incorrect texts for me.
![image](https://cloud.githubusercontent.com/assets/493140/25217631/ed742004-25a7-11e7-9513-11a46eec5ec1.png)

**Comment by corradio** [comment]
I actually just merged the pull request, and am pushing a new version out now.
Once that is done, the app should update automatically, without needing to push a new apk (we use https://microsoft.github.io/code-push/).
